In [9]:
import torch

In [53]:
v1 = torch.tensor(-1.0)
v2 = torch.tensor(1.)
v = v1 - v2

In [66]:
data = [-0.4301,  0.3461, -0.8389, -0.8988,  0.4395,  0.2668, -0.6573, -0.4025,
        -0.1955,  0.8036, -0.6360, -0.9323, -0.0178,  0.1041, -0.1297,  0.5402,
         0.4044, -0.5942,  0.8601,  0.8345]
pred = torch.tensor(data)
pred.shape

torch.Size([20])

In [78]:
r1 = torch.tensor(-0.5, dtype=torch.float32)
r2 = torch.tensor(0.5, dtype=torch.float32)

In [79]:
expected_loss = torch.tensor([0.0, 0.0, 0.3389, 0.3988, 0.0, 0.0, 0.1573, 0.0, 0.0, 0.3036, 0.1360, 0.4323, 0.0, 0.0, 0.0, 0.0402, 0.0, 0.0942, 0.3601, 0.3345])
expected_loss

tensor([0.0000, 0.0000, 0.3389, 0.3988, 0.0000, 0.0000, 0.1573, 0.0000, 0.0000,
        0.3036, 0.1360, 0.4323, 0.0000, 0.0000, 0.0000, 0.0402, 0.0000, 0.0942,
        0.3601, 0.3345])

In [80]:
masking_r1 = pred < r1
masking_r1 = masking_r1.int()
masking_r1

tensor([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       dtype=torch.int32)

In [81]:
l1 = r1 - pred
l1

tensor([-0.0699, -0.8461,  0.3389,  0.3988, -0.9395, -0.7668,  0.1573, -0.0975,
        -0.3045, -1.3036,  0.1360,  0.4323, -0.4822, -0.6041, -0.3703, -1.0402,
        -0.9044,  0.0942, -1.3601, -1.3345])

In [82]:
l1 = l1.mul(masking_r1)
l1

tensor([-0.0000, -0.0000, 0.3389, 0.3988, -0.0000, -0.0000, 0.1573, -0.0000, -0.0000,
        -0.0000, 0.1360, 0.4323, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 0.0942,
        -0.0000, -0.0000])

In [88]:
masking_r2 = r2 < pred
masking_r2 = masking_r2.int()
masking_r2

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       dtype=torch.int32)

In [89]:
l2 = pred - r2
l2

tensor([-0.9301, -0.1539, -1.3389, -1.3988, -0.0605, -0.2332, -1.1573, -0.9025,
        -0.6955,  0.3036, -1.1360, -1.4323, -0.5178, -0.3959, -0.6297,  0.0402,
        -0.0956, -1.0942,  0.3601,  0.3345])

In [90]:
l2 = l2.mul(masking_r2)
l2

tensor([-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
        0.3036, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 0.0402, -0.0000, -0.0000,
        0.3601, 0.3345])

In [91]:
l = l1 +  l2
l

tensor([-0.0000, -0.0000, 0.3389, 0.3988, -0.0000, -0.0000, 0.1573, -0.0000, -0.0000,
        0.3036, 0.1360, 0.4323, -0.0000, -0.0000, -0.0000, 0.0402, -0.0000, 0.0942,
        0.3601, 0.3345])

In [92]:
expected_loss

tensor([0.0000, 0.0000, 0.3389, 0.3988, 0.0000, 0.0000, 0.1573, 0.0000, 0.0000,
        0.3036, 0.1360, 0.4323, 0.0000, 0.0000, 0.0000, 0.0402, 0.0000, 0.0942,
        0.3601, 0.3345])