In [43]:
import spacy

In [44]:
nlp = spacy.load('en_core_web_lg')

In [45]:
len(nlp.vocab.vectors)

514157

In [46]:
items = nlp.vocab.vectors.items()
items

In [47]:
item = next(items)
item

(2667587279770775948,
 array([ 1.4633e+00,  9.8817e-01, -3.0328e+00, -4.5657e+00,  5.2594e+00,
         4.9401e+00,  1.9530e+00,  1.1014e+00,  1.9144e+00,  1.2517e+00,
         4.1602e+00, -2.4509e-01, -2.8326e+00,  7.0372e+00,  3.1470e+00,
        -1.4404e+00,  3.5250e-01, -3.9967e+00, -1.2175e+00, -9.6799e+00,
        -2.2389e+00,  8.3774e-01, -2.5347e-01, -2.1523e+00, -6.0064e+00,
        -1.2502e-01, -4.5116e+00, -8.6450e-01,  1.9007e+00,  4.6967e+00,
        -2.5936e+00, -7.9161e+00, -1.8016e+00, -5.0156e+00, -5.5539e+00,
         4.3324e+00,  3.7273e-01,  3.5302e+00,  1.2176e+00,  7.1263e+00,
         5.2715e-01,  2.8144e+00,  9.4242e-01, -3.4059e+00, -2.6015e+00,
         3.4317e-01, -2.1145e+00, -4.0966e+00, -1.3031e+00, -1.2101e-01,
        -6.9779e-01,  4.1269e+00, -1.4083e-01, -2.1014e+00,  2.4622e+00,
         3.3071e+00, -4.2257e+00, -3.1965e+00,  2.2212e+00,  5.3073e+00,
         1.1388e+00, -4.9430e+00,  5.5804e-01, -6.3739e-01,  4.0619e+00,
         3.9589e-01, -2.0400e

In [48]:
key = item[0]
key

2667587279770775948

In [49]:
nlp.vocab.strings[key]

'</s>'

In [29]:
key == nlp.vocab.strings['</s>']

True

In [16]:
all(nlp.vocab.vectors[key] == item[1])

True

In [20]:
all(nlp.vocab['</s>'].vector == item[1])

True

In [104]:
doc = nlp('Bored bank customers flock to day-trading platforms during pandemic')
token = doc[1]
token

bank

In [105]:
token.lex.orth

579043611916083110

In [106]:
all(nlp.vocab.vectors[token.lex.orth] == token.vector)

True

In [107]:
indexes = {}
for idx, (key, _) in enumerate(nlp.vocab.vectors.items()):
    indexes[key] = idx

In [108]:
len(indexes.keys())

514157

In [109]:
indexes[579043611916083110]

1535

In [110]:
indexes[2667587279770775948]

0

In [111]:
vectors = list(nlp.vocab.vectors.values())
vectors[0:1000]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [112]:
 nlp.vocab.vectors.find(row=indexes[579043611916083110]) == 579043611916083110

True

In [133]:
nlp.vocab.vectors.find(key=579043611916083110)

1535

In [114]:
vectors[nlp.vocab.vectors.find(key=579043611916083110)]

1535

In [115]:
vectors[1535]

1535

In [180]:
nlp.vocab.vectors.shape

(514157, 300)

In [182]:
nlp.vocab.vectors.resize((nlp.vocab.vectors.shape[0] + 1, nlp.vocab.vectors.shape[1]))

[]

In [183]:
nlp.vocab.vectors.shape

(514158, 300)

In [184]:
id = nlp.vocab.strings["vector_zero"]
nlp.vocab.vectors.add(id, vector=np.zeros(300))

514157

In [165]:
[nlp.vocab.vectors.find(key=token.lex.orth) for token in doc]

[48920, 1535, 976, 16555, 5, 162, 9, 3022, 3863, 201, 1088]

In [188]:
wv = map(lambda item: item[1], nlp.vocab.vectors.items())

In [189]:
wv = list(wv)

In [190]:
len(wv)

514158

In [153]:
[all(wv[nlp.vocab.vectors.find(key=token.lex.orth)] == token.vector)  for token in doc]

[True, True, True, True, True, True, True, True, True, True, True]

In [121]:
import torch
from torch import nn
import numpy as np

In [191]:
class SentenceEmbedding(nn.Module):
    def __init__(self):
        super(SentenceEmbedding, self).__init__()
        weight = torch.FloatTensor(np.array(wv))
        self.embedding = nn.Embedding.from_pretrained(weight)
    def forward(self, input):
        return self.embedding(input)

In [192]:
model = SentenceEmbedding()

In [193]:
input = torch.LongTensor([[1535, 514157, 514157]])
output = model(input)

In [139]:
output.shape

torch.Size([1, 3, 300])

In [140]:
np_vector = output[0][0].numpy()

In [152]:
all(np_vector == token.vector)

True

In [194]:
output[0][1].numpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [196]:
id = nlp.vocab.strings["vector_zero"]
wv[nlp.vocab.vectors.find(key=id)]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [98]:
import spacy
import numpy as np
from datasets import load_dataset
from torch.utils.data import DataLoader
from torch import nn
import torch

In [89]:
nlp = spacy.load('en_core_web_lg')
print(len(nlp.vocab.vectors))

514157


In [90]:
nlp.vocab.vectors.resize((nlp.vocab.vectors.shape[0] + 1, nlp.vocab.vectors.shape[1]))
item_id = nlp.vocab.strings.add("vector_zero")
nlp.vocab.vectors.add(item_id, vector=np.zeros(300, dtype=np.float32))

514157

In [91]:
len(nlp.vocab.vectors)

514158

In [107]:
def vectorise_sequence(nlp, fixed_sequence_length, samples):
    data = []
    vector_zero_key = nlp.vocab.strings["vector_zero"]
    vector_zero_idx = nlp.vocab.vectors.find(key=vector_zero_key)
    for sample_ in samples:
        sample = [nlp.vocab.vectors.find(key=token.lex.orth) for token in nlp(sample_)]
        length = len(sample)
        padlen = fixed_sequence_length - length
        if padlen >= 0:
           padding = [vector_zero_idx for _ in range(padlen)]
           sample = sample + padding
        else:
           sample = sample[0:fixed_sequence_length]

        data.append(sample)

    return data


def dataset_map_fn(nlp, fixed_sequence_length):

    def dataset_map(samples):
        sample1 = vectorise_sequence(nlp, fixed_sequence_length, samples['sample1'])
        sample2 = vectorise_sequence(nlp, fixed_sequence_length, samples['sample2'])

        return {
            'sample1': sample1,
            'sample2': sample2,
            'random_similarity': samples['random_similarity']
        }

    return dataset_map


def get_word_vector_matrix(nlp, device):
    wv = map(lambda item: item[1], nlp.vocab.vectors.items())
    wv = np.array(list(wv))
    return torch.FloatTensor(np.array(wv, dtype=np.float32)).to(device)


dataset_map = dataset_map_fn(nlp, 14)

ds = load_dataset(
    'csv',
    data_files='sentence_embedding_training_data/samples.csv',
    delimiter='\t', split='train'
)
ds = ds.map(dataset_map, keep_in_memory=True, batched=True, num_proc=1)
ds = ds.with_format('torch', device='cpu')
dataloader = DataLoader(ds, batch_size=3, shuffle=True)
word_embedding = nn.Embedding.from_pretrained(get_word_vector_matrix(nlp, 'cpu'))
for data in dataloader:
    print('sample1: ', data['sample1'].shape, data['sample1'])
    encoded = word_embedding(data['sample1'])
    print(encoded.shape)
    print(encoded[:, :, 0:5])

Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 156.56 examples/s]


sample1:  torch.Size([3, 14]) tensor([[217706,   6870,    240,    488,   8373,   9487, 514157, 514157, 514157,
         514157, 514157, 514157, 514157, 514157],
        [  1329,    829,   6732,    241,     28,   2283,      4,  28196, 514157,
         514157, 514157, 514157, 514157, 514157],
        [     7,   2892,   1682,     13,   3495,   1804,   7401, 514157, 514157,
         514157, 514157, 514157, 514157, 514157]])
torch.Size([3, 14, 300])
tensor([[[ 7.9455e-02,  3.7691e-01,  2.8806e-02, -2.1682e-01, -4.3071e-03],
         [ 1.2945e+00,  5.6324e+00, -1.3994e+00, -1.4660e+00,  3.9272e+00],
         [-5.4382e+00, -9.7478e-01, -2.1477e+00,  4.9361e+00,  4.5397e+00],
         [-1.0656e-01, -5.3104e-01, -2.9488e+00,  2.6521e-01,  3.7485e+00],
         [-2.4263e+00, -2.3096e+00, -5.2258e-01, -5.9937e-02,  2.7323e+00],
         [-1.4146e+00, -3.4400e+00,  1.2449e+00,  2.7117e+00,  3.2055e-01],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+

In [93]:
# aba decides against community broadcasting licence [217706, 6870, 240, 488, 8373, 9487, 514157, 514157, 514157, 514157, 514157, 514157, 514157, 514157]
sequence = [217706, 6870, 240, 488, 8373, 9487, 514157, 514157, 514157, 514157, 514157, 514157, 514157, 514157]
for idx in sequence:
    k = nlp.vocab.vectors.find(row=idx)
    print(nlp.vocab.strings[k])

aba
decides
against
community
broadcasting
licence
vector_zero
vector_zero
vector_zero
vector_zero
vector_zero
vector_zero
vector_zero
vector_zero


In [94]:
# community bank shares trading shows little change [488, 1535, 3070, 3022, 827, 207, 407, 514157, 514157, 514157, 514157, 514157, 514157, 514157]
sequence = [488, 1535, 3070, 3022, 827, 207, 407, 514157, 514157, 514157, 514157, 514157, 514157, 514157]
for idx in sequence:
    k = nlp.vocab.vectors.find(row=idx)
    print(nlp.vocab.strings[k])

community
bank
shares
trading
shows
little
change
vector_zero
vector_zero
vector_zero
vector_zero
vector_zero
vector_zero
vector_zero
